# using traefik
# see documentation on https://doc.traefik.io/traefik/getting-started/quick-start/

version: "3.4"
services:
  start:
    image: 'golang:1.13.15-alpine'
    volumes:
      - ./config/nginx/app.conf:/etc/nginx/conf.d/default.conf

  web:
    build:
      context: .
      dockerfile: DockerFile
      target: builder
    ports:
    - 9000:9000
    - 8080:8080
    volumes:
    - ./router/:/usr/local/go/src/entityValidator.com/router/
    - ./request/:/usr/local/go/src/entityValidator.com/request/
    - ./:/go/src/entityValidator.com/
    command: reflex -r "\.go$$" -s -- sh -c "go run /go/src/entityValidator.com/main.go"


